<a href="https://colab.research.google.com/github/coding-dojo-data-science/data-enrichment-practice-solutions/blob/main/Wk9_SQLBasicsSolutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>
<img src="https://course_report_production.s3.amazonaws.com/rich/rich_files/rich_files/2470/s300/cd-logo-blue-600x600.png" alt="Coding Dojo Logo" class="center" height="50">

# SQL Basics - Solutions

In [ ]:
# Added on 05/16/23 to address new errors
!pip install --upgrade 'sqlalchemy<2.0'

Collecting sqlalchemy<2.0
  Downloading SQLAlchemy-1.4.49-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 18.7 MB/s eta 0:00:00
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy<2.0) (2.0.2)
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.18
    Uninstalling SQLAlchemy-2.0.18:
      Successfully uninstalled SQLAlchemy-2.0.18
Successfully installed sqlalchemy-1.4.49

In [ ]:
# Confirm version is <2.0
import sqlalchemy
sqlalchemy.__version__

'1.4.49'

In [ ]:
# imports
import pandas as pd
from sqlalchemy import create_engine
pd.set_option('display.max_columns',50)

In [ ]:
# Save the file id from the Share URL
FILEID = "15zRAJ98a-WO8Nt0U3IACZM8zFl1SAkCi"
# Set the output filename
FILENAME = 'schools.db'
# Run wget command (web-get)
!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id={FILEID}' -O {FILENAME}

--2023-07-17 18:43:00--  https://docs.google.com/uc?export=download&id=15zRAJ98a-WO8Nt0U3IACZM8zFl1SAkCi
Resolving docs.google.com (docs.google.com)... 172.217.203.100, 172.217.203.139, 172.217.203.138, ...
Connecting to docs.google.com (docs.google.com)|172.217.203.100|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-0o-c0-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/7uk7mpmo7itan8ailrvq9hj7jp7gmrup/1689619350000/07032743932305917350/*/15zRAJ98a-WO8Nt0U3IACZM8zFl1SAkCi?e=download&uuid=204f3078-9187-4569-b4ed-d495053c5534 [following]
Warning: wildcards not supported in HTTP.
--2023-07-17 18:43:00--  https://doc-0o-c0-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/7uk7mpmo7itan8ailrvq9hj7jp7gmrup/1689619350000/07032743932305917350/*/15zRAJ98a-WO8Nt0U3IACZM8zFl1SAkCi?e=download&uuid=204f3078-9187-4569-b4ed-d495053c5534
Resolving doc-0o-c0-docs.googleusercontent.com (doc-0o-c0-docs.googleusercontent.com)... 74.125.141.132, 2607:f8b0:400c:c06::84
Connecting to doc-0o-c0-docs.googleusercontent.com (doc-0o-c0-docs.googleusercontent.com)|74.125.141.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 581632 (568K) [application/octet-stream]
Saving to: ‘schools.db’

schools.db          100%[===================>] 568.00K  --.-KB/s    in 0.01s

2023-07-17 18:43:00 (54.7 MB/s) - ‘schools.db’ saved [581632/581632]

In [ ]:
# create sqlite engine for a database called schools
engine = create_engine('sqlite:///schools.db')
# create connection to database via the engine
conn = engine.connect()

In [ ]:
## check what tables are included in the database
q = """SELECT * FROM sqlite_master"""
pd.read_sql(q, conn)

,type,name,tbl_name,rootpage,sql
0,table,school_details,school_details,2,"CREATE TABLE school_details (\n\t""DistrictName..."
1,table,facility_details,facility_details,4,"CREATE TABLE facility_details (\n\t""Establishm..."

## SELECT & FROM

1. Get the EstablishmentName, SchoolLevel, and Website columns.

In [ ]:
# Write your SQL query in this string
q = """
SELECT EstablishmentName, SchoolLevel, Website
FROM school_details;
"""

# Read the sql query into pandas to view the results
pd.read_sql(q, conn)

,EstablishmentName,SchoolLevel,Website
0,BUDANG GOVERNMENT PRIMARY SCHOOL (E),PS,None
1,CENTRAL PENDAM GOVERNMENT SENIOR SECONDARY SCHOOL,SSS,None
2,"CENTRAL POINT ACADEMY, CENTRAL PENDAM",SS,www.facebook.com/khanalkeshav (Group-CPA)
3,CHEURIBOTEY GOVERNMENT JUNIOR HIGH SCHOOL (E),JHS,None
4,DUGA GOVERNMENT SECONDARY SCHOOL,SS,None
...,...,...,...
1244,MANGSABONG GOVERNMENT PRIMARY SCHOOL,PS,None
1245,MANGTABONG GOVERNMENT PRIMARY SCHOOL(SSA),PS,None
1246,"NEW HORIZON ACADEMY, LASSO(TASHIDING)",PS,None
1247,TINGTING GAON GOVERNMENT PRIMARY SCHOOL,PS,None
1248,TSONG GOVERNMENT PRIMARY SCHOOL,PS,None

## WHERE

2. Display the EstablishmentName and DistrictHQDistance (in Km) for schools where the DistrictHQDistance (in Km) is more than 100 Km.

In [ ]:
# Write your SQL query in this string
q = """
SELECT EstablishmentName, `DistrictHQDistance (in Km)`
FROM school_details
WHERE "DistrictHQDistance (in Km)" > 100;
"""

# Read the sql query into pandas to view the results
pd.read_sql(q, conn)

                                EstablishmentName  DistrictHQDistance (in Km)
0              DODACHEN GOVERNMENT PRIMARY SCHOOL                       150.0
1               DEOLING GOVERNMENT PRIMARY SCHOOL                       107.0
2                   PEMA TSEL ACADEMY(PHADAMCHEN)                       110.0
3                ZULUCK GOVERNMENT PRIMARY SCHOOL                       120.0
4               BHARENG GOVERNMENT PRIMARY SCHOOL                       150.0
5                HIMALAYAN RISING ACADEMY, OKHREY                       103.0
6             PIUREYTAR GOVERNMENT PRIMARY SCHOOL                       102.0
7               RIBDI GOVERNMENT SECONDARY SCHOOL                       120.0
8  MILLING KARMATAR GOVERNMENT JUNIOR HIGH SCHOOL                       170.0
9       SORENG GOVERNMENT SENIOR SECONDARY SCHOOL                       115.0

3. Display the EstablishmentName, SchoolLevel, DistrictHQDistance (in Km) for schools where the school level is "JHS."

In [ ]:
# Write your SQL query in this string
q = """
SELECT EstablishmentName, SchoolLevel, `DistrictHQDistance (in Km)`
FROM school_details
WHERE SchoolLevel = 'JHS';
"""

# Read the sql query into pandas to view the results
pd.read_sql(q, conn)

,EstablishmentName,SchoolLevel,DistrictHQDistance (in Km)
0,CHEURIBOTEY GOVERNMENT JUNIOR HIGH SCHOOL (E),JHS,60.0
1,"PADMA KUMARI PUBLIC SCHOOL, DUGA",JHS,48.0
2,SAJONG GOVERNMENT JUNIOR HIGH SCHOOL,JHS,57.0
3,SINGLEYBONG GOVERNMENT JUNIOR HIGH SCHOOL,JHS,38.0
4,"SUNRISE ACADEMY, DUGA",JHS,47.0
...,...,...,...
335,TIMBRONG GOVERNMENT JUNIOR HIGH SCHOOL,JHS,32.0
336,"VIDYA SAGAR GYANPETH, TATHANG",JHS,25.0
337,"HIMALAYAN RADIANT ACADEMY, TASHIDING",JHS,35.0
338,"GOOD SHEPHERD NURSERY SCHOOL , YUKSAM",JHS,52.0
339,"LIFE VISION ACADEMY, YUKSAM",JHS,32.0

## Wildcards & LIKE

4. Display the EstablishmentName, SchoolLevel, DistrictHQDistance (in Km) for schools where the name of the school contains the words "JUNIOR HIGH."

In [ ]:
# Write your SQL query in this string
q = """
SELECT EstablishmentName, SchoolLevel, "DistrictHQDistance (in Km)"
FROM school_details
WHERE EstablishmentName LIKE '%JUNIOR HIGH%';
"""

# Read the sql query into pandas to view the results
pd.read_sql(q, conn)

,EstablishmentName,SchoolLevel,DistrictHQDistance (in Km)
0,CHEURIBOTEY GOVERNMENT JUNIOR HIGH SCHOOL (E),JHS,60.0
1,SAJONG GOVERNMENT JUNIOR HIGH SCHOOL,JHS,57.0
2,SINGLEYBONG GOVERNMENT JUNIOR HIGH SCHOOL,JHS,38.0
3,BORDANG GOVERNMENT JUNIOR HIGH SCHOOL,JHS,33.0
4,RANGPO BAZAR GOVERNMENT JUNIOR HIGH SCHOOL,JHS,47.0
...,...,...,...
179,TAMATAM GOVERNMENT JUNIOR HIGH SCHOOL,JHS,55.0
180,UPPER GERETHANG GOVERNMENT JUNIOR HIGH SCHOOL,JHS,60.0
181,DARAPTHANG GOVERNMENT JUNIOR HIGH SCHOOL,JHS,28.0
182,MIDDLE CHONGRANG GOVERNMENT JUNIOR HIGH SCHOOL,JHS,60.0
183,TIMBRONG GOVERNMENT JUNIOR HIGH SCHOOL,JHS,32.0

## LIMIT & ORDER BY

5. Display the EstablishmentName, SchoolLevel, DistrictHQDistance (in Km) for schools where the name of the school starts with the letter "C." Sort the results alphabetically by school name and limit the results of the query to 10 rows.

In [ ]:
# Write your SQL query in this string
q = """
SELECT EstablishmentName, SchoolLevel, "DistrictHQDistance (in Km)"
FROM school_details
WHERE EstablishmentName LIKE 'C%'
ORDER BY EstablishmentName
LIMIT 10
"""

# Read the sql query into pandas to view the results
pd.read_sql(q, conn)

,EstablishmentName,SchoolLevel,DistrictHQDistance (in Km)
0,C.M.RAI GOVERNMENT SECONDARY SCHOOL (OMCHU),SS,26.0
1,"CANAAN SCHOOL, RANIPOOL",JHS,0.0
2,"CANARY BIRD ACADEMY, KARTOK",PS,38.0
3,"CAROL ACADEMY, YANGSUM UPPER BERFOK",JHS,50.0
4,CENTRAL MARTAM GOVERNMENT JUNIOR SCHOOL,JHS,50.0
5,CENTRAL PATUK GOVERNMENT PRIMARY SCHOOL,PS,48.0
6,CENTRAL PENDAM GOVERNMENT SENIOR SECONDARY SCHOOL,SSS,50.0
7,"CENTRAL POINT ACADEMY, CENTRAL PENDAM",SS,49.0
8,"CENTRAL SCHOOL FOR TIBETAN , RAVANGLA",JHS,26.0
9,CHAKUNG GOVERNMENT SENIOR SECONDARY SCHOOL,SSS,55.0

6. Display the names of schools in urban areas. Sort the results in reverse alphabetical order.

In [ ]:
# Write your SQL query in this string
q = """
SELECT EstablishmentName
FROM school_details
WHERE LocatedInRuralOrUrban LIKE 'Urban%'
ORDER BY EstablishmentName DESC
"""

# Read the sql query into pandas to view the results
pd.read_sql_query(q, conn)

                                      EstablishmentName
0                      ZULUCK GOVERNMENT PRIMARY SCHOOL
1                      ZOOM GOVERNMENT SECONDARY SCHOOL
2                 ZITLANG GOVERNMENT JUNIOR HIGH SCHOOL
3                      ZINGLA GOVERNMENT PRIMARY SCHOOL
4                                  ZENITH PUBLIC SCHOOL
...                                                 ...
1127                AARUBOTEY GOVERNMENT PRIMARY SCHOOL
1128                  AAPGAZI GOVERNMENT PRIMARY SCHOOL
1129             4TH MILE GOVERNMENT JUNIOR HIGH SCHOOL
1130                10TH MILE GOVERNMENT PRIMARY SCHOOL
1131  (I.E.C) INDIAN EVANGALISTIC CRUSADE MISSION PR...

[1132 rows x 1 columns]

In [ ]:
# Close the database connection
conn.close()